version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
    - run:
        name: compile egg
        command: |
          python3 setup.py bdist_egg
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
    - run:
        name: run tests
        command: |
          . venv/bin/activate
          nosetests
          python3 setup.py develop
    - store_artifacts:
        path: test-reports
        destination: test-reports
